inicio
	varinicio
		lit A lit;
		B int;
		D int;;;;
		C real;
	varfim;
	escreva "Digite B";
	leia B
	escreva "Digite A:";
	leia A;
	se(B<A)
		entao entao
		se(B<=A))
			entao
			escreva "B esta entre 2 e 4";
		fimse
	fimse a{81u381u21hdscskbasbdhabdkasbdad1301230-23971786(!&@#&^#&*!&#*#()}
	B<-B+4;
	B<-B+2;
	B<-B+3;
	D<-B;
	C<-50.2E-3;
	escreva "\nB=\n";
	escreva D inicio;
	escreva "\n";
	escreva C;
	escreva "\n";
	escreva A;
fim